### ISSUE TITLE
update function calls for httpsig NewSigner and SignRequest

### ISSUE THREAD

**Issue by ghost** [writeas/activityserve#1]
after https://github.com/go-fed/httpsig/commit/8d61ea6a9aa6290011d37b815fbca0beed6819ff the signatures for httpsig.NewSigner and signer.SignRequest have changed.

we should either update the calls or use modules to pin down a version.

**Comment by fbaube** [comment]
I am encountering this bug, in httpsig.NewSigner . 
Can someone propose a workaround ? 
It requires a valid value of httpsig.DigestAlgorithm . 
The error:
# github.com/writeas/activityserve
../../writeas/activityserve/actor.go:457:39: not enough arguments in call to httpsig.NewSigner
	have ([]httpsig.Algorithm, string, []string, httpsig.SignatureScheme)
	want ([]httpsig.Algorithm, httpsig.DigestAlgorithm, []string, httpsig.SignatureScheme, int64)
../../writeas/activityserve/actor.go:524:35: not enough arguments in call to httpsig.NewSigner
	have ([]httpsig.Algorithm, string, []string, httpsig.SignatureScheme)
	want ([]httpsig.Algorithm, httpsig.DigestAlgorithm, []string, httpsig.SignatureScheme, int64)
make: *** [run] Error 2

**Comment by thebaer** [comment]
Hmm, I did actually address this in 10584314ee41136f83517d88ed4075e811bc6d4f with Go modules. So you shouldn't see this issue as long as Go modules are enabled. Which version of Go are you running, @fbaube?

**Comment by fbaube** [comment]
You are correct. After i enabled modules, the error went away. My apologies.

**Comment by thebaer** [comment]
No worries! I'll take this as a reminder to close this :slightly_smiling_face:
